/** P2.1 — ~45 liquid NSE names (Nifty50-ish), multi-sector. Do not invent prices. */

export const SCREEN_UNIVERSE = [
  // Banks / Financials
  "HDFCBANK",
  "ICICIBANK",
  "SBIN",
  "AXISBANK",
  "KOTAKBANK",
  "INDUSINDBK",
  "BANKBARODA",
  "BAJFINANCE",
  "BAJAJFINSV",
  "HDFCLIFE",
  "SBILIFE",
  // IT
  "TCS",
  "INFY",
  "HCLTECH",
  "WIPRO",
  "TECHM",
  "LTIM",
  // Energy / Oil / Power
  "RELIANCE",
  "ONGC",
  "NTPC",
  "POWERGRID",
  "COALINDIA",
  "IOC",
  "BPCL",
  // Pharma
  "SUNPHARMA",
  "CIPLA",
  "DRREDDY",
  "DIVISLAB",
  // Auto
  "TMPV", // Tata Motors Passenger Vehicles (TATAMOTORS.NS delisted on Yahoo after demerger; TMPV.NS verified 2026-09-25)
  "MARUTI",
  "M&M",
  "BAJAJ-AUTO",
  "EICHERMOT",
  "HEROMOTOCO",
  // FMCG / Consumer
  "HINDUNILVR",
  "ITC",
  "NESTLEIND",
  "BRITANNIA",
  "TATACONSUM",
  "ASIANPAINT",
  "TITAN",
  // Metals
  "TATASTEEL",
  "JSWSTEEL",
  "HINDALCO",
  "VEDL",
  // Infra / Cap goods / Conglomerate
  "LT",
  "ADANIENT",
  "ADANIPORTS",
  "ULTRACEMCO",
  "GRASIM",
  // Telecom / Defence
  "BHARTIARTL",
  "BEL",
] as const;

export type ScreenTicker = (typeof SCREEN_UNIVERSE)[number];

const SECTOR: Record<string, string> = {
  HDFCBANK: "Banks",
  ICICIBANK: "Banks",
  SBIN: "Banks",
  AXISBANK: "Banks",
  KOTAKBANK: "Banks",
  INDUSINDBK: "Banks",
  BANKBARODA: "Banks",
  BAJFINANCE: "Finance",
  BAJAJFINSV: "Finance",
  HDFCLIFE: "Finance",
  SBILIFE: "Finance",
  TCS: "IT",
  INFY: "IT",
  HCLTECH: "IT",
  WIPRO: "IT",
  TECHM: "IT",
  LTIM: "IT",
  RELIANCE: "Energy",
  ONGC: "Energy",
  NTPC: "Energy",
  POWERGRID: "Energy",
  COALINDIA: "Energy",
  IOC: "Energy",
  BPCL: "Energy",
  SUNPHARMA: "Pharma",
  CIPLA: "Pharma",
  DRREDDY: "Pharma",
  DIVISLAB: "Pharma",
  TMPV: "Auto",
  MARUTI: "Auto",
  "M&M": "Auto",
  "BAJAJ-AUTO": "Auto",
  EICHERMOT: "Auto",
  HEROMOTOCO: "Auto",
  HINDUNILVR: "FMCG",
  ITC: "FMCG",
  NESTLEIND: "FMCG",
  BRITANNIA: "FMCG",
  TATACONSUM: "FMCG",
  ASIANPAINT: "FMCG",
  TITAN: "FMCG",
  TATASTEEL: "Metals",
  JSWSTEEL: "Metals",
  HINDALCO: "Metals",
  VEDL: "Metals",
  LT: "Infra",
  ADANIENT: "Infra",
  ADANIPORTS: "Infra",
  ULTRACEMCO: "Cement",
  GRASIM: "Cement",
  BHARTIARTL: "Telecom",
  BEL: "Defence",
};

export const SCREEN_SECTORS = [
  "Banks",
  "Finance",
  "IT",
  "Energy",
  "Pharma",
  "Auto",
  "FMCG",
  "Metals",
  "Infra",
  "Cement",
  "Telecom",
  "Defence",
] as const;

export function screenSectorOf(ticker: string): string {
  return SECTOR[ticker.toUpperCase()] || "Unknown";
}
